/* Generated by re2c 0.13.5 on Mon Sep 12 15:38:40 2011 */

// To generate this file run: re2c -b -i -w RelevanceLexer.re2c > RelevanceLexer.cpp

#include "RelevanceLexer.h"

RelevanceLexer::RelevanceLexer()
{
	Reset();
}

void RelevanceLexer::Reset()
{
	m_start = 0;
	m_end = 0;
	m_cursor = 0;
	m_marker = 0;
	m_ctxmarker = 0;
}

RelevanceToken RelevanceLexer::NextToken()
{
	m_marker    = m_cursor;
	m_ctxmarker = m_cursor;


{
	UTF16::Unit yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,  32,  32,  32,  32,  32,  32,  32, 
		 32, 160, 160,  32,  32, 160,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		160,  32,   0,  32,  32,  32,  32,  48, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112,  32,  32,  32,  32,  32,  32, 
		 32,  48,  48,  48,  48,  48,  48,  48, 
		 48,  48,  48,  48,  48,  48,  48,  48, 
		 48,  48,  48,  48,  48,  48,  48,  48, 
		 48,  48,  48,  32,  32,  32,  32,  48, 
		 32,  48,  48,  48,  48,  48,  48,  48, 
		 48,  48,  48,  48,  48,  48,  48,  48, 
		 48,  48,  48,  48,  48,  48,  48,  48, 
		 48,  48,  48,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
		 32,  32,  32,  32,  32,  32,  32,  32, 
	};

	if ((m_end - m_cursor) < 32) { Fill(); }
	yych = *m_cursor;
	switch (yych) {
	case 0x0000:	goto yy47;
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy2;
	case '!':	goto yy26;
	case '"':	goto yy6;
	case '&':	goto yy27;
	case '(':	goto yy22;
	case ')':	goto yy24;
	case '*':	goto yy29;
	case '+':	goto yy31;
	case ',':	goto yy33;
	case '-':	goto yy35;
	case '/':	goto yy37;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy4;
	case ';':	goto yy39;
	case '<':	goto yy41;
	case '=':	goto yy43;
	case '>':	goto yy45;
	case 'A':
	case 'a':	goto yy8;
	case 'B':
	case 'G':
	case 'H':
	case 'J':
	case 'K':
	case 'L':
	case 'P':
	case 'Q':
	case 'R':
	case 'U':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'p':
	case 'q':
	case 'r':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy10;
	case 'C':
	case 'c':	goto yy11;
	case 'D':
	case 'd':	goto yy12;
	case 'E':
	case 'e':	goto yy13;
	case 'F':
	case 'f':	goto yy14;
	case 'I':
	case 'i':	goto yy15;
	case 'M':
	case 'm':	goto yy16;
	case 'N':
	case 'n':	goto yy17;
	case 'O':
	case 'o':	goto yy18;
	case 'S':
	case 's':	goto yy19;
	case 'T':
	case 't':	goto yy20;
	case 'W':
	case 'w':	goto yy21;
	default:	goto yy49;
	}
yy2:
	++m_cursor;
	yych = *m_cursor;
	goto yy459;
yy3:
	{ return RelevanceToken::t_whitespace; }
yy4:
	++m_cursor;
	yych = *m_cursor;
	goto yy457;
yy5:
	{ return RelevanceToken::t_number; }
yy6:
	m_ctxmarker = m_cursor + 1;
	yyaccept = 0;
	yych = *(m_marker = ++m_cursor);
	goto yy451;
yy7:
	{ return RelevanceToken::t_illegal; }
yy8:
	m_ctxmarker = m_cursor + 1;
	++m_cursor;
	if ((yych = *m_cursor) <= 'S') {
		if (yych <= '9') {
			if (yych == '\'') goto yy57;
			if (yych <= '/') goto yy441;
			goto yy57;
		} else {
			if (yych <= 'M') {
				if (yych <= '@') goto yy441;
				goto yy57;
			} else {
				if (yych <= 'N') goto yy440;
				if (yych <= 'R') goto yy57;
				goto yy439;
			}
		}
	} else {
		if (yych <= 'm') {
			if (yych <= '^') {
				if (yych <= 'Z') goto yy57;
				goto yy441;
			} else {
				if (yych == '`') goto yy441;
				goto yy57;
			}
		} else {
			if (yych <= 'r') {
				if (yych <= 'n') goto yy440;
				goto yy57;
			} else {
				if (yych <= 's') goto yy439;
				if (yych <= 'z') goto yy57;
				goto yy441;
			}
		}
	}
yy9:
	{ return RelevanceToken::t_word; }
yy10:
	yych = *++m_cursor;
	goto yy58;
yy11:
	yych = *++m_cursor;
	if (yych == 'O') goto yy430;
	if (yych == 'o') goto yy430;
	goto yy58;
yy12:
	yych = *++m_cursor;
	if (yych == 'O') goto yy385;
	if (yych == 'o') goto yy385;
	goto yy58;
yy13:
	yych = *++m_cursor;
	if (yych <= 'X') {
		if (yych <= 'N') {
			if (yych == 'L') goto yy347;
			if (yych <= 'M') goto yy58;
			goto yy346;
		} else {
			if (yych == 'Q') goto yy345;
			if (yych <= 'W') goto yy58;
			goto yy344;
		}
	} else {
		if (yych <= 'n') {
			if (yych == 'l') goto yy347;
			if (yych <= 'm') goto yy58;
			goto yy346;
		} else {
			if (yych <= 'q') {
				if (yych <= 'p') goto yy58;
				goto yy345;
			} else {
				if (yych == 'x') goto yy344;
				goto yy58;
			}
		}
	}
yy14:
	yych = *++m_cursor;
	if (yych == 'A') goto yy338;
	if (yych == 'a') goto yy338;
	goto yy58;
yy15:
	yych = *++m_cursor;
	if (yych <= 'T') {
		if (yych <= 'F') {
			if (yych <= 'E') goto yy58;
			goto yy163;
		} else {
			if (yych <= 'R') goto yy58;
			if (yych <= 'S') goto yy162;
			goto yy161;
		}
	} else {
		if (yych <= 'r') {
			if (yych == 'f') goto yy163;
			goto yy58;
		} else {
			if (yych <= 's') goto yy162;
			if (yych <= 't') goto yy161;
			goto yy58;
		}
	}
yy16:
	yych = *++m_cursor;
	if (yych == 'O') goto yy157;
	if (yych == 'o') goto yy157;
	goto yy58;
yy17:
	yych = *++m_cursor;
	if (yych <= 'U') {
		if (yych == 'O') goto yy147;
		if (yych <= 'T') goto yy58;
		goto yy146;
	} else {
		if (yych <= 'o') {
			if (yych <= 'n') goto yy58;
			goto yy147;
		} else {
			if (yych == 'u') goto yy146;
			goto yy58;
		}
	}
yy18:
	yych = *++m_cursor;
	if (yych <= 'R') {
		if (yych == 'F') goto yy141;
		if (yych <= 'Q') goto yy58;
		goto yy140;
	} else {
		if (yych <= 'f') {
			if (yych <= 'e') goto yy58;
			goto yy141;
		} else {
			if (yych == 'r') goto yy140;
			goto yy58;
		}
	}
yy19:
	yych = *++m_cursor;
	if (yych == 'T') goto yy128;
	if (yych == 't') goto yy128;
	goto yy58;
yy20:
	yych = *++m_cursor;
	if (yych <= 'R') {
		if (yych == 'H') goto yy65;
		if (yych <= 'Q') goto yy58;
		goto yy64;
	} else {
		if (yych <= 'h') {
			if (yych <= 'g') goto yy58;
			goto yy65;
		} else {
			if (yych == 'r') goto yy64;
			goto yy58;
		}
	}
yy21:
	yych = *++m_cursor;
	if (yych == 'H') goto yy56;
	if (yych == 'h') goto yy56;
	goto yy58;
yy22:
	++m_cursor;
	{ return RelevanceToken::t_openParen; }
yy24:
	++m_cursor;
	{ return RelevanceToken::t_closeParen; }
yy26:
	yych = *++m_cursor;
	if (yych == '=') goto yy54;
	goto yy7;
yy27:
	++m_cursor;
	{ return RelevanceToken::t_concat; }
yy29:
	++m_cursor;
	{ return RelevanceToken::t_star; }
yy31:
	++m_cursor;
	{ return RelevanceToken::t_plus; }
yy33:
	++m_cursor;
	{ return RelevanceToken::t_comma; }
yy35:
	++m_cursor;
	{ return RelevanceToken::t_minus; }
yy37:
	++m_cursor;
	{ return RelevanceToken::t_slash; }
yy39:
	++m_cursor;
	{ return RelevanceToken::t_semiColon; }
yy41:
	++m_cursor;
	if ((yych = *m_cursor) == '=') goto yy52;
	{ return RelevanceToken::t_less; }
yy43:
	++m_cursor;
	{ return RelevanceToken::t_equal; }
yy45:
	++m_cursor;
	if ((yych = *m_cursor) == '=') goto yy50;
	{ return RelevanceToken::t_greater; }
yy47:
	++m_cursor;
	{ return RelevanceToken::t_endOfInput; }
yy49:
	yych = *++m_cursor;
	goto yy7;
yy50:
	++m_cursor;
	{ return RelevanceToken::t_greaterOrEqual; }
yy52:
	++m_cursor;
	{ return RelevanceToken::t_lessOrEqual; }
yy54:
	++m_cursor;
	{ return RelevanceToken::t_notEqual; }
yy56:
	yych = *++m_cursor;
	if (yych == 'O') goto yy59;
	if (yych == 'o') goto yy59;
	goto yy58;
yy57:
	++m_cursor;
	if (m_end <= m_cursor) { Fill(); }
	yych = *m_cursor;
yy58:
	if (yych & ~0xFF) {
		goto yy9;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	goto yy9;
yy59:
	yych = *++m_cursor;
	if (yych == 'S') goto yy60;
	if (yych != 's') goto yy58;
yy60:
	yych = *++m_cursor;
	if (yych == 'E') goto yy61;
	if (yych != 'e') goto yy58;
yy61:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_whose; }
yy64:
	yych = *++m_cursor;
	if (yych == 'U') goto yy124;
	if (yych == 'u') goto yy124;
	goto yy58;
yy65:
	yych = *++m_cursor;
	if (yych == 'E') goto yy66;
	if (yych != 'e') goto yy58;
yy66:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= 'R') {
		if (yych <= '9') {
			if (yych == '\'') goto yy57;
			if (yych <= '/') goto yy69;
			goto yy57;
		} else {
			if (yych <= 'M') {
				if (yych <= '@') goto yy69;
				goto yy57;
			} else {
				if (yych <= 'N') goto yy68;
				if (yych <= 'Q') goto yy57;
			}
		}
	} else {
		if (yych <= 'm') {
			if (yych <= '^') {
				if (yych <= 'Z') goto yy57;
				goto yy69;
			} else {
				if (yych == '`') goto yy69;
				goto yy57;
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'n') goto yy68;
				goto yy57;
			} else {
				if (yych <= 'r') goto yy67;
				if (yych <= 'z') goto yy57;
				goto yy69;
			}
		}
	}
yy67:
	yych = *++m_cursor;
	if (yych == 'E') goto yy73;
	if (yych == 'e') goto yy73;
	goto yy58;
yy68:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy71;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	goto yy71;
yy69:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_ignored; }
yy71:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_then; }
yy73:
	yyaccept = 1;
	yych = *(m_marker = ++m_cursor);
	if (yych != ' ') goto yy58;
	yych = *++m_cursor;
	if (yych <= 'E') {
		if (yych <= 'C') goto yy75;
		if (yych <= 'D') goto yy76;
		goto yy77;
	} else {
		if (yych <= 'c') goto yy75;
		if (yych <= 'd') goto yy76;
		if (yych <= 'e') goto yy77;
	}
yy75:
	m_cursor = m_marker;
	if (yyaccept <= 5) {
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy7;
				} else {
					goto yy9;
				}
			} else {
				goto yy84;
			}
		} else {
			if (yyaccept <= 4) {
				if (yyaccept <= 3) {
					goto yy91;
				} else {
					goto yy167;
				}
			} else {
				goto yy208;
			}
		}
	} else {
		if (yyaccept <= 8) {
			if (yyaccept <= 7) {
				if (yyaccept <= 6) {
					goto yy232;
				} else {
					goto yy250;
				}
			} else {
				goto yy290;
			}
		} else {
			if (yyaccept <= 10) {
				if (yyaccept <= 9) {
					goto yy314;
				} else {
					goto yy372;
				}
			} else {
				goto yy379;
			}
		}
	}
yy76:
	yych = *++m_cursor;
	if (yych == 'O') goto yy97;
	if (yych == 'o') goto yy97;
	goto yy75;
yy77:
	yych = *++m_cursor;
	if (yych == 'X') goto yy78;
	if (yych != 'x') goto yy75;
yy78:
	yych = *++m_cursor;
	if (yych == 'I') goto yy79;
	if (yych != 'i') goto yy75;
yy79:
	yych = *++m_cursor;
	if (yych == 'S') goto yy80;
	if (yych != 's') goto yy75;
yy80:
	yych = *++m_cursor;
	if (yych == 'T') goto yy81;
	if (yych != 't') goto yy75;
yy81:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= 'R') {
		if (yych <= '\'') {
			if (yych == ' ') goto yy83;
			if (yych <= '&') goto yy85;
			goto yy75;
		} else {
			if (yych <= '/') goto yy85;
			if (yych <= '9') goto yy75;
			if (yych <= '@') goto yy85;
			goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'S') goto yy82;
			if (yych <= 'Z') goto yy75;
			if (yych <= '^') goto yy85;
			goto yy75;
		} else {
			if (yych <= 'r') {
				if (yych <= '`') goto yy85;
				goto yy75;
			} else {
				if (yych <= 's') goto yy82;
				if (yych <= 'z') goto yy75;
				goto yy85;
			}
		}
	}
yy82:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '9') {
		if (yych <= '&') {
			if (yych == ' ') goto yy92;
			goto yy90;
		} else {
			if (yych <= '\'') goto yy75;
			if (yych <= '/') goto yy90;
			goto yy75;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy90;
			if (yych <= 'Z') goto yy75;
			goto yy90;
		} else {
			if (yych == '`') goto yy90;
			if (yych <= 'z') goto yy75;
			goto yy90;
		}
	}
yy83:
	yyaccept = 2;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'N') goto yy86;
	if (yych == 'n') goto yy86;
yy84:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_exists; }
yy85:
	yych = *++m_cursor;
	goto yy84;
yy86:
	yych = *++m_cursor;
	if (yych == 'O') goto yy87;
	if (yych != 'o') goto yy75;
yy87:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy88;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy88;
			if (yych <= 'z') goto yy75;
		}
	}
yy88:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notExists; }
yy90:
	++m_cursor;
yy91:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_exists; }
yy92:
	yyaccept = 3;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'N') goto yy93;
	if (yych != 'n') goto yy91;
yy93:
	yych = *++m_cursor;
	if (yych == 'O') goto yy94;
	if (yych != 'o') goto yy75;
yy94:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy95;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy95;
			if (yych <= 'z') goto yy75;
		}
	}
yy95:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notExists; }
yy97:
	yych = *++m_cursor;
	if (yych <= 'D') {
		if (yych != ' ') goto yy75;
	} else {
		if (yych <= 'E') goto yy99;
		if (yych == 'e') goto yy99;
		goto yy75;
	}
	yych = *++m_cursor;
	if (yych == 'N') goto yy113;
	if (yych == 'n') goto yy113;
	goto yy75;
yy99:
	yych = *++m_cursor;
	if (yych == 'S') goto yy100;
	if (yych != 's') goto yy75;
yy100:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'N') goto yy102;
	if (yych != 'n') goto yy75;
yy102:
	yych = *++m_cursor;
	if (yych == 'O') goto yy103;
	if (yych != 'o') goto yy75;
yy103:
	yych = *++m_cursor;
	if (yych == 'T') goto yy104;
	if (yych != 't') goto yy75;
yy104:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'E') goto yy106;
	if (yych != 'e') goto yy75;
yy106:
	yych = *++m_cursor;
	if (yych == 'X') goto yy107;
	if (yych != 'x') goto yy75;
yy107:
	yych = *++m_cursor;
	if (yych == 'I') goto yy108;
	if (yych != 'i') goto yy75;
yy108:
	yych = *++m_cursor;
	if (yych == 'S') goto yy109;
	if (yych != 's') goto yy75;
yy109:
	yych = *++m_cursor;
	if (yych == 'T') goto yy110;
	if (yych != 't') goto yy75;
yy110:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy111;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy111;
			if (yych <= 'z') goto yy75;
		}
	}
yy111:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notExists; }
yy113:
	yych = *++m_cursor;
	if (yych == 'O') goto yy114;
	if (yych != 'o') goto yy75;
yy114:
	yych = *++m_cursor;
	if (yych == 'T') goto yy115;
	if (yych != 't') goto yy75;
yy115:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'E') goto yy117;
	if (yych != 'e') goto yy75;
yy117:
	yych = *++m_cursor;
	if (yych == 'X') goto yy118;
	if (yych != 'x') goto yy75;
yy118:
	yych = *++m_cursor;
	if (yych == 'I') goto yy119;
	if (yych != 'i') goto yy75;
yy119:
	yych = *++m_cursor;
	if (yych == 'S') goto yy120;
	if (yych != 's') goto yy75;
yy120:
	yych = *++m_cursor;
	if (yych == 'T') goto yy121;
	if (yych != 't') goto yy75;
yy121:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy122;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy122;
			if (yych <= 'z') goto yy75;
		}
	}
yy122:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notExists; }
yy124:
	yych = *++m_cursor;
	if (yych == 'E') goto yy125;
	if (yych != 'e') goto yy58;
yy125:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_true; }
yy128:
	yych = *++m_cursor;
	if (yych == 'A') goto yy129;
	if (yych != 'a') goto yy58;
yy129:
	yych = *++m_cursor;
	if (yych == 'R') goto yy130;
	if (yych != 'r') goto yy58;
yy130:
	yych = *++m_cursor;
	if (yych == 'T') goto yy131;
	if (yych != 't') goto yy58;
yy131:
	yych = *++m_cursor;
	if (yych == 'S') goto yy132;
	if (yych != 's') goto yy58;
yy132:
	yyaccept = 1;
	yych = *(m_marker = ++m_cursor);
	if (yych != ' ') goto yy58;
	yych = *++m_cursor;
	if (yych == 'W') goto yy134;
	if (yych != 'w') goto yy75;
yy134:
	yych = *++m_cursor;
	if (yych == 'I') goto yy135;
	if (yych != 'i') goto yy75;
yy135:
	yych = *++m_cursor;
	if (yych == 'T') goto yy136;
	if (yych != 't') goto yy75;
yy136:
	yych = *++m_cursor;
	if (yych == 'H') goto yy137;
	if (yych != 'h') goto yy75;
yy137:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy138;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy138;
			if (yych <= 'z') goto yy75;
		}
	}
yy138:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_startsWith; }
yy140:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy144;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	goto yy144;
yy141:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_of; }
yy144:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_or; }
yy146:
	yych = *++m_cursor;
	if (yych == 'M') goto yy151;
	if (yych == 'm') goto yy151;
	goto yy58;
yy147:
	yych = *++m_cursor;
	if (yych == 'T') goto yy148;
	if (yych != 't') goto yy58;
yy148:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_not; }
yy151:
	yych = *++m_cursor;
	if (yych == 'B') goto yy152;
	if (yych != 'b') goto yy58;
yy152:
	yych = *++m_cursor;
	if (yych == 'E') goto yy153;
	if (yych != 'e') goto yy58;
yy153:
	yych = *++m_cursor;
	if (yych == 'R') goto yy154;
	if (yych != 'r') goto yy58;
yy154:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_phraseNumber; }
yy157:
	yych = *++m_cursor;
	if (yych == 'D') goto yy158;
	if (yych != 'd') goto yy58;
yy158:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_mod; }
yy161:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= 'E') {
		if (yych <= '/') {
			if (yych == '\'') goto yy57;
			goto yy330;
		} else {
			if (yych <= '9') goto yy57;
			if (yych <= '@') goto yy330;
			if (yych <= 'D') goto yy57;
			goto yy329;
		}
	} else {
		if (yych <= '`') {
			if (yych <= 'Z') goto yy57;
			if (yych == '_') goto yy57;
			goto yy330;
		} else {
			if (yych == 'e') goto yy329;
			if (yych <= 'z') goto yy57;
			goto yy330;
		}
	}
yy162:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy166;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	if (yych == ' ') goto yy168;
	goto yy166;
yy163:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_if; }
yy166:
	++m_cursor;
yy167:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_equal; }
yy168:
	yyaccept = 4;
	yych = *(m_marker = ++m_cursor);
	switch (yych) {
	case 'C':
	case 'c':	goto yy173;
	case 'E':
	case 'e':	goto yy172;
	case 'G':
	case 'g':	goto yy171;
	case 'L':
	case 'l':	goto yy170;
	case 'N':
	case 'n':	goto yy169;
	default:	goto yy167;
	}
yy169:
	yych = *++m_cursor;
	if (yych == 'O') goto yy247;
	if (yych == 'o') goto yy247;
	goto yy75;
yy170:
	yych = *++m_cursor;
	if (yych == 'E') goto yy223;
	if (yych == 'e') goto yy223;
	goto yy75;
yy171:
	yych = *++m_cursor;
	if (yych == 'R') goto yy196;
	if (yych == 'r') goto yy196;
	goto yy75;
yy172:
	yych = *++m_cursor;
	if (yych == 'Q') goto yy187;
	if (yych == 'q') goto yy187;
	goto yy75;
yy173:
	yych = *++m_cursor;
	if (yych == 'O') goto yy174;
	if (yych != 'o') goto yy75;
yy174:
	yych = *++m_cursor;
	if (yych == 'N') goto yy175;
	if (yych != 'n') goto yy75;
yy175:
	yych = *++m_cursor;
	if (yych == 'T') goto yy176;
	if (yych != 't') goto yy75;
yy176:
	yych = *++m_cursor;
	if (yych == 'A') goto yy177;
	if (yych != 'a') goto yy75;
yy177:
	yych = *++m_cursor;
	if (yych == 'I') goto yy178;
	if (yych != 'i') goto yy75;
yy178:
	yych = *++m_cursor;
	if (yych == 'N') goto yy179;
	if (yych != 'n') goto yy75;
yy179:
	yych = *++m_cursor;
	if (yych == 'E') goto yy180;
	if (yych != 'e') goto yy75;
yy180:
	yych = *++m_cursor;
	if (yych == 'D') goto yy181;
	if (yych != 'd') goto yy75;
yy181:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'B') goto yy183;
	if (yych != 'b') goto yy75;
yy183:
	yych = *++m_cursor;
	if (yych == 'Y') goto yy184;
	if (yych != 'y') goto yy75;
yy184:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy185;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy185;
			if (yych <= 'z') goto yy75;
		}
	}
yy185:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_containedBy; }
yy187:
	yych = *++m_cursor;
	if (yych == 'U') goto yy188;
	if (yych != 'u') goto yy75;
yy188:
	yych = *++m_cursor;
	if (yych == 'A') goto yy189;
	if (yych != 'a') goto yy75;
yy189:
	yych = *++m_cursor;
	if (yych == 'L') goto yy190;
	if (yych != 'l') goto yy75;
yy190:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy192;
	if (yych != 't') goto yy75;
yy192:
	yych = *++m_cursor;
	if (yych == 'O') goto yy193;
	if (yych != 'o') goto yy75;
yy193:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy194;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy194;
			if (yych <= 'z') goto yy75;
		}
	}
yy194:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_equal; }
yy196:
	yych = *++m_cursor;
	if (yych == 'E') goto yy197;
	if (yych != 'e') goto yy75;
yy197:
	yych = *++m_cursor;
	if (yych == 'A') goto yy198;
	if (yych != 'a') goto yy75;
yy198:
	yych = *++m_cursor;
	if (yych == 'T') goto yy199;
	if (yych != 't') goto yy75;
yy199:
	yych = *++m_cursor;
	if (yych == 'E') goto yy200;
	if (yych != 'e') goto yy75;
yy200:
	yych = *++m_cursor;
	if (yych == 'R') goto yy201;
	if (yych != 'r') goto yy75;
yy201:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy203;
	if (yych != 't') goto yy75;
yy203:
	yych = *++m_cursor;
	if (yych == 'H') goto yy204;
	if (yych != 'h') goto yy75;
yy204:
	yych = *++m_cursor;
	if (yych == 'A') goto yy205;
	if (yych != 'a') goto yy75;
yy205:
	yych = *++m_cursor;
	if (yych == 'N') goto yy206;
	if (yych != 'n') goto yy75;
yy206:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '9') {
		if (yych <= '&') {
			if (yych != ' ') goto yy209;
		} else {
			if (yych <= '\'') goto yy75;
			if (yych <= '/') goto yy209;
			goto yy75;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy209;
			if (yych <= 'Z') goto yy75;
			goto yy209;
		} else {
			if (yych == '`') goto yy209;
			if (yych <= 'z') goto yy75;
			goto yy209;
		}
	}
	yyaccept = 5;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'O') goto yy210;
	if (yych == 'o') goto yy210;
yy208:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_greater; }
yy209:
	yych = *++m_cursor;
	goto yy208;
yy210:
	yych = *++m_cursor;
	if (yych == 'R') goto yy211;
	if (yych != 'r') goto yy75;
yy211:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'E') goto yy213;
	if (yych != 'e') goto yy75;
yy213:
	yych = *++m_cursor;
	if (yych == 'Q') goto yy214;
	if (yych != 'q') goto yy75;
yy214:
	yych = *++m_cursor;
	if (yych == 'U') goto yy215;
	if (yych != 'u') goto yy75;
yy215:
	yych = *++m_cursor;
	if (yych == 'A') goto yy216;
	if (yych != 'a') goto yy75;
yy216:
	yych = *++m_cursor;
	if (yych == 'L') goto yy217;
	if (yych != 'l') goto yy75;
yy217:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy219;
	if (yych != 't') goto yy75;
yy219:
	yych = *++m_cursor;
	if (yych == 'O') goto yy220;
	if (yych != 'o') goto yy75;
yy220:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy221;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy221;
			if (yych <= 'z') goto yy75;
		}
	}
yy221:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_greaterOrEqual; }
yy223:
	yych = *++m_cursor;
	if (yych == 'S') goto yy224;
	if (yych != 's') goto yy75;
yy224:
	yych = *++m_cursor;
	if (yych == 'S') goto yy225;
	if (yych != 's') goto yy75;
yy225:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy227;
	if (yych != 't') goto yy75;
yy227:
	yych = *++m_cursor;
	if (yych == 'H') goto yy228;
	if (yych != 'h') goto yy75;
yy228:
	yych = *++m_cursor;
	if (yych == 'A') goto yy229;
	if (yych != 'a') goto yy75;
yy229:
	yych = *++m_cursor;
	if (yych == 'N') goto yy230;
	if (yych != 'n') goto yy75;
yy230:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '9') {
		if (yych <= '&') {
			if (yych == ' ') goto yy233;
		} else {
			if (yych <= '\'') goto yy75;
			if (yych >= '0') goto yy75;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy231;
			if (yych <= 'Z') goto yy75;
		} else {
			if (yych == '`') goto yy231;
			if (yych <= 'z') goto yy75;
		}
	}
yy231:
	++m_cursor;
yy232:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_less; }
yy233:
	yyaccept = 6;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'O') goto yy234;
	if (yych != 'o') goto yy232;
yy234:
	yych = *++m_cursor;
	if (yych == 'R') goto yy235;
	if (yych != 'r') goto yy75;
yy235:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'E') goto yy237;
	if (yych != 'e') goto yy75;
yy237:
	yych = *++m_cursor;
	if (yych == 'Q') goto yy238;
	if (yych != 'q') goto yy75;
yy238:
	yych = *++m_cursor;
	if (yych == 'U') goto yy239;
	if (yych != 'u') goto yy75;
yy239:
	yych = *++m_cursor;
	if (yych == 'A') goto yy240;
	if (yych != 'a') goto yy75;
yy240:
	yych = *++m_cursor;
	if (yych == 'L') goto yy241;
	if (yych != 'l') goto yy75;
yy241:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy243;
	if (yych != 't') goto yy75;
yy243:
	yych = *++m_cursor;
	if (yych == 'O') goto yy244;
	if (yych != 'o') goto yy75;
yy244:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy245;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy245;
			if (yych <= 'z') goto yy75;
		}
	}
yy245:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_lessOrEqual; }
yy247:
	yych = *++m_cursor;
	if (yych == 'T') goto yy248;
	if (yych != 't') goto yy75;
yy248:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '9') {
		if (yych <= '&') {
			if (yych == ' ') goto yy251;
		} else {
			if (yych <= '\'') goto yy75;
			if (yych >= '0') goto yy75;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy249;
			if (yych <= 'Z') goto yy75;
		} else {
			if (yych == '`') goto yy249;
			if (yych <= 'z') goto yy75;
		}
	}
yy249:
	++m_cursor;
yy250:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notEqual; }
yy251:
	yyaccept = 7;
	yych = *(m_marker = ++m_cursor);
	switch (yych) {
	case 'C':
	case 'c':	goto yy255;
	case 'E':
	case 'e':	goto yy254;
	case 'G':
	case 'g':	goto yy253;
	case 'L':
	case 'l':	goto yy252;
	default:	goto yy250;
	}
yy252:
	yych = *++m_cursor;
	if (yych == 'E') goto yy305;
	if (yych == 'e') goto yy305;
	goto yy75;
yy253:
	yych = *++m_cursor;
	if (yych == 'R') goto yy278;
	if (yych == 'r') goto yy278;
	goto yy75;
yy254:
	yych = *++m_cursor;
	if (yych == 'Q') goto yy269;
	if (yych == 'q') goto yy269;
	goto yy75;
yy255:
	yych = *++m_cursor;
	if (yych == 'O') goto yy256;
	if (yych != 'o') goto yy75;
yy256:
	yych = *++m_cursor;
	if (yych == 'N') goto yy257;
	if (yych != 'n') goto yy75;
yy257:
	yych = *++m_cursor;
	if (yych == 'T') goto yy258;
	if (yych != 't') goto yy75;
yy258:
	yych = *++m_cursor;
	if (yych == 'A') goto yy259;
	if (yych != 'a') goto yy75;
yy259:
	yych = *++m_cursor;
	if (yych == 'I') goto yy260;
	if (yych != 'i') goto yy75;
yy260:
	yych = *++m_cursor;
	if (yych == 'N') goto yy261;
	if (yych != 'n') goto yy75;
yy261:
	yych = *++m_cursor;
	if (yych == 'E') goto yy262;
	if (yych != 'e') goto yy75;
yy262:
	yych = *++m_cursor;
	if (yych == 'D') goto yy263;
	if (yych != 'd') goto yy75;
yy263:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'B') goto yy265;
	if (yych != 'b') goto yy75;
yy265:
	yych = *++m_cursor;
	if (yych == 'Y') goto yy266;
	if (yych != 'y') goto yy75;
yy266:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy267;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy267;
			if (yych <= 'z') goto yy75;
		}
	}
yy267:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notContainedBy; }
yy269:
	yych = *++m_cursor;
	if (yych == 'U') goto yy270;
	if (yych != 'u') goto yy75;
yy270:
	yych = *++m_cursor;
	if (yych == 'A') goto yy271;
	if (yych != 'a') goto yy75;
yy271:
	yych = *++m_cursor;
	if (yych == 'L') goto yy272;
	if (yych != 'l') goto yy75;
yy272:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy274;
	if (yych != 't') goto yy75;
yy274:
	yych = *++m_cursor;
	if (yych == 'O') goto yy275;
	if (yych != 'o') goto yy75;
yy275:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy276;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy276;
			if (yych <= 'z') goto yy75;
		}
	}
yy276:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notEqual; }
yy278:
	yych = *++m_cursor;
	if (yych == 'E') goto yy279;
	if (yych != 'e') goto yy75;
yy279:
	yych = *++m_cursor;
	if (yych == 'A') goto yy280;
	if (yych != 'a') goto yy75;
yy280:
	yych = *++m_cursor;
	if (yych == 'T') goto yy281;
	if (yych != 't') goto yy75;
yy281:
	yych = *++m_cursor;
	if (yych == 'E') goto yy282;
	if (yych != 'e') goto yy75;
yy282:
	yych = *++m_cursor;
	if (yych == 'R') goto yy283;
	if (yych != 'r') goto yy75;
yy283:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy285;
	if (yych != 't') goto yy75;
yy285:
	yych = *++m_cursor;
	if (yych == 'H') goto yy286;
	if (yych != 'h') goto yy75;
yy286:
	yych = *++m_cursor;
	if (yych == 'A') goto yy287;
	if (yych != 'a') goto yy75;
yy287:
	yych = *++m_cursor;
	if (yych == 'N') goto yy288;
	if (yych != 'n') goto yy75;
yy288:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '9') {
		if (yych <= '&') {
			if (yych != ' ') goto yy291;
		} else {
			if (yych <= '\'') goto yy75;
			if (yych <= '/') goto yy291;
			goto yy75;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy291;
			if (yych <= 'Z') goto yy75;
			goto yy291;
		} else {
			if (yych == '`') goto yy291;
			if (yych <= 'z') goto yy75;
			goto yy291;
		}
	}
	yyaccept = 8;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'O') goto yy292;
	if (yych == 'o') goto yy292;
yy290:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notGreater; }
yy291:
	yych = *++m_cursor;
	goto yy290;
yy292:
	yych = *++m_cursor;
	if (yych == 'R') goto yy293;
	if (yych != 'r') goto yy75;
yy293:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'E') goto yy295;
	if (yych != 'e') goto yy75;
yy295:
	yych = *++m_cursor;
	if (yych == 'Q') goto yy296;
	if (yych != 'q') goto yy75;
yy296:
	yych = *++m_cursor;
	if (yych == 'U') goto yy297;
	if (yych != 'u') goto yy75;
yy297:
	yych = *++m_cursor;
	if (yych == 'A') goto yy298;
	if (yych != 'a') goto yy75;
yy298:
	yych = *++m_cursor;
	if (yych == 'L') goto yy299;
	if (yych != 'l') goto yy75;
yy299:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy301;
	if (yych != 't') goto yy75;
yy301:
	yych = *++m_cursor;
	if (yych == 'O') goto yy302;
	if (yych != 'o') goto yy75;
yy302:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy303;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy303;
			if (yych <= 'z') goto yy75;
		}
	}
yy303:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notGreaterOrEqual; }
yy305:
	yych = *++m_cursor;
	if (yych == 'S') goto yy306;
	if (yych != 's') goto yy75;
yy306:
	yych = *++m_cursor;
	if (yych == 'S') goto yy307;
	if (yych != 's') goto yy75;
yy307:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy309;
	if (yych != 't') goto yy75;
yy309:
	yych = *++m_cursor;
	if (yych == 'H') goto yy310;
	if (yych != 'h') goto yy75;
yy310:
	yych = *++m_cursor;
	if (yych == 'A') goto yy311;
	if (yych != 'a') goto yy75;
yy311:
	yych = *++m_cursor;
	if (yych == 'N') goto yy312;
	if (yych != 'n') goto yy75;
yy312:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '9') {
		if (yych <= '&') {
			if (yych == ' ') goto yy315;
		} else {
			if (yych <= '\'') goto yy75;
			if (yych >= '0') goto yy75;
		}
	} else {
		if (yych <= '^') {
			if (yych <= '@') goto yy313;
			if (yych <= 'Z') goto yy75;
		} else {
			if (yych == '`') goto yy313;
			if (yych <= 'z') goto yy75;
		}
	}
yy313:
	++m_cursor;
yy314:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notLess; }
yy315:
	yyaccept = 9;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'O') goto yy316;
	if (yych != 'o') goto yy314;
yy316:
	yych = *++m_cursor;
	if (yych == 'R') goto yy317;
	if (yych != 'r') goto yy75;
yy317:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'E') goto yy319;
	if (yych != 'e') goto yy75;
yy319:
	yych = *++m_cursor;
	if (yych == 'Q') goto yy320;
	if (yych != 'q') goto yy75;
yy320:
	yych = *++m_cursor;
	if (yych == 'U') goto yy321;
	if (yych != 'u') goto yy75;
yy321:
	yych = *++m_cursor;
	if (yych == 'A') goto yy322;
	if (yych != 'a') goto yy75;
yy322:
	yych = *++m_cursor;
	if (yych == 'L') goto yy323;
	if (yych != 'l') goto yy75;
yy323:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'T') goto yy325;
	if (yych != 't') goto yy75;
yy325:
	yych = *++m_cursor;
	if (yych == 'O') goto yy326;
	if (yych != 'o') goto yy75;
yy326:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy327;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy327;
			if (yych <= 'z') goto yy75;
		}
	}
yy327:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notLessOrEqual; }
yy329:
	yych = *++m_cursor;
	if (yych == 'M') goto yy332;
	if (yych == 'm') goto yy332;
	goto yy58;
yy330:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_it; }
yy332:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= 'S') {
		if (yych <= '/') {
			if (yych == '\'') goto yy57;
			goto yy334;
		} else {
			if (yych <= '9') goto yy57;
			if (yych <= '@') goto yy334;
			if (yych <= 'R') goto yy57;
		}
	} else {
		if (yych <= '`') {
			if (yych <= 'Z') goto yy57;
			if (yych == '_') goto yy57;
			goto yy334;
		} else {
			if (yych == 's') goto yy333;
			if (yych <= 'z') goto yy57;
			goto yy334;
		}
	}
yy333:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy336;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	goto yy336;
yy334:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_phraseItem; }
yy336:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_phraseItems; }
yy338:
	yych = *++m_cursor;
	if (yych == 'L') goto yy339;
	if (yych != 'l') goto yy58;
yy339:
	yych = *++m_cursor;
	if (yych == 'S') goto yy340;
	if (yych != 's') goto yy58;
yy340:
	yych = *++m_cursor;
	if (yych == 'E') goto yy341;
	if (yych != 'e') goto yy58;
yy341:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_false; }
yy344:
	yych = *++m_cursor;
	if (yych == 'I') goto yy367;
	if (yych == 'i') goto yy367;
	goto yy58;
yy345:
	yych = *++m_cursor;
	if (yych == 'U') goto yy361;
	if (yych == 'u') goto yy361;
	goto yy58;
yy346:
	yych = *++m_cursor;
	if (yych == 'D') goto yy352;
	if (yych == 'd') goto yy352;
	goto yy58;
yy347:
	yych = *++m_cursor;
	if (yych == 'S') goto yy348;
	if (yych != 's') goto yy58;
yy348:
	yych = *++m_cursor;
	if (yych == 'E') goto yy349;
	if (yych != 'e') goto yy58;
yy349:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_else; }
yy352:
	yych = *++m_cursor;
	if (yych == 'S') goto yy353;
	if (yych != 's') goto yy58;
yy353:
	yyaccept = 1;
	yych = *(m_marker = ++m_cursor);
	if (yych != ' ') goto yy58;
	yych = *++m_cursor;
	if (yych == 'W') goto yy355;
	if (yych != 'w') goto yy75;
yy355:
	yych = *++m_cursor;
	if (yych == 'I') goto yy356;
	if (yych != 'i') goto yy75;
yy356:
	yych = *++m_cursor;
	if (yych == 'T') goto yy357;
	if (yych != 't') goto yy75;
yy357:
	yych = *++m_cursor;
	if (yych == 'H') goto yy358;
	if (yych != 'h') goto yy75;
yy358:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy359;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy359;
			if (yych <= 'z') goto yy75;
		}
	}
yy359:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_endsWith; }
yy361:
	yych = *++m_cursor;
	if (yych == 'A') goto yy362;
	if (yych != 'a') goto yy58;
yy362:
	yych = *++m_cursor;
	if (yych == 'L') goto yy363;
	if (yych != 'l') goto yy58;
yy363:
	yych = *++m_cursor;
	if (yych == 'S') goto yy364;
	if (yych != 's') goto yy58;
yy364:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_equal; }
yy367:
	yych = *++m_cursor;
	if (yych == 'S') goto yy368;
	if (yych != 's') goto yy58;
yy368:
	yych = *++m_cursor;
	if (yych == 'T') goto yy369;
	if (yych != 't') goto yy58;
yy369:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= 'R') {
		if (yych <= '\'') {
			if (yych == ' ') goto yy371;
			if (yych <= '&') goto yy373;
			goto yy57;
		} else {
			if (yych <= '/') goto yy373;
			if (yych <= '9') goto yy57;
			if (yych <= '@') goto yy373;
			goto yy57;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'S') goto yy370;
			if (yych <= 'Z') goto yy57;
			if (yych <= '^') goto yy373;
			goto yy57;
		} else {
			if (yych <= 'r') {
				if (yych <= '`') goto yy373;
				goto yy57;
			} else {
				if (yych <= 's') goto yy370;
				if (yych <= 'z') goto yy57;
				goto yy373;
			}
		}
	}
yy370:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy378;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	if (yych == ' ') goto yy380;
	goto yy378;
yy371:
	yyaccept = 10;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'N') goto yy374;
	if (yych == 'n') goto yy374;
yy372:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_exists; }
yy373:
	yych = *++m_cursor;
	goto yy372;
yy374:
	yych = *++m_cursor;
	if (yych == 'O') goto yy375;
	if (yych != 'o') goto yy75;
yy375:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy376;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy376;
			if (yych <= 'z') goto yy75;
		}
	}
yy376:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notExists; }
yy378:
	++m_cursor;
yy379:
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_exists; }
yy380:
	yyaccept = 11;
	yych = *(m_marker = ++m_cursor);
	if (yych == 'N') goto yy381;
	if (yych != 'n') goto yy379;
yy381:
	yych = *++m_cursor;
	if (yych == 'O') goto yy382;
	if (yych != 'o') goto yy75;
yy382:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy383;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy383;
			if (yych <= 'z') goto yy75;
		}
	}
yy383:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notExists; }
yy385:
	yych = *++m_cursor;
	if (yych == 'E') goto yy386;
	if (yych != 'e') goto yy58;
yy386:
	yych = *++m_cursor;
	if (yych == 'S') goto yy387;
	if (yych != 's') goto yy58;
yy387:
	yyaccept = 1;
	yych = *(m_marker = ++m_cursor);
	if (yych != ' ') goto yy58;
	yych = *++m_cursor;
	if (yych == 'N') goto yy389;
	if (yych != 'n') goto yy75;
yy389:
	yych = *++m_cursor;
	if (yych == 'O') goto yy390;
	if (yych != 'o') goto yy75;
yy390:
	yych = *++m_cursor;
	if (yych == 'T') goto yy391;
	if (yych != 't') goto yy75;
yy391:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych <= 'S') {
		if (yych <= 'D') {
			if (yych == 'C') goto yy395;
			goto yy75;
		} else {
			if (yych <= 'E') goto yy394;
			if (yych <= 'R') goto yy75;
		}
	} else {
		if (yych <= 'd') {
			if (yych == 'c') goto yy395;
			goto yy75;
		} else {
			if (yych <= 'e') goto yy394;
			if (yych != 's') goto yy75;
		}
	}
	yych = *++m_cursor;
	if (yych == 'T') goto yy419;
	if (yych == 't') goto yy419;
	goto yy75;
yy394:
	yych = *++m_cursor;
	if (yych <= 'Q') {
		if (yych == 'N') goto yy404;
		if (yych <= 'P') goto yy75;
		goto yy405;
	} else {
		if (yych <= 'n') {
			if (yych <= 'm') goto yy75;
			goto yy404;
		} else {
			if (yych == 'q') goto yy405;
			goto yy75;
		}
	}
yy395:
	yych = *++m_cursor;
	if (yych == 'O') goto yy396;
	if (yych != 'o') goto yy75;
yy396:
	yych = *++m_cursor;
	if (yych == 'N') goto yy397;
	if (yych != 'n') goto yy75;
yy397:
	yych = *++m_cursor;
	if (yych == 'T') goto yy398;
	if (yych != 't') goto yy75;
yy398:
	yych = *++m_cursor;
	if (yych == 'A') goto yy399;
	if (yych != 'a') goto yy75;
yy399:
	yych = *++m_cursor;
	if (yych == 'I') goto yy400;
	if (yych != 'i') goto yy75;
yy400:
	yych = *++m_cursor;
	if (yych == 'N') goto yy401;
	if (yych != 'n') goto yy75;
yy401:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy402;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy402;
			if (yych <= 'z') goto yy75;
		}
	}
yy402:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notContains; }
yy404:
	yych = *++m_cursor;
	if (yych == 'D') goto yy411;
	if (yych == 'd') goto yy411;
	goto yy75;
yy405:
	yych = *++m_cursor;
	if (yych == 'U') goto yy406;
	if (yych != 'u') goto yy75;
yy406:
	yych = *++m_cursor;
	if (yych == 'A') goto yy407;
	if (yych != 'a') goto yy75;
yy407:
	yych = *++m_cursor;
	if (yych == 'L') goto yy408;
	if (yych != 'l') goto yy75;
yy408:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy409;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy409;
			if (yych <= 'z') goto yy75;
		}
	}
yy409:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notEqual; }
yy411:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'W') goto yy413;
	if (yych != 'w') goto yy75;
yy413:
	yych = *++m_cursor;
	if (yych == 'I') goto yy414;
	if (yych != 'i') goto yy75;
yy414:
	yych = *++m_cursor;
	if (yych == 'T') goto yy415;
	if (yych != 't') goto yy75;
yy415:
	yych = *++m_cursor;
	if (yych == 'H') goto yy416;
	if (yych != 'h') goto yy75;
yy416:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy417;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy417;
			if (yych <= 'z') goto yy75;
		}
	}
yy417:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notEndsWith; }
yy419:
	yych = *++m_cursor;
	if (yych == 'A') goto yy420;
	if (yych != 'a') goto yy75;
yy420:
	yych = *++m_cursor;
	if (yych == 'R') goto yy421;
	if (yych != 'r') goto yy75;
yy421:
	yych = *++m_cursor;
	if (yych == 'T') goto yy422;
	if (yych != 't') goto yy75;
yy422:
	yych = *++m_cursor;
	if (yych != ' ') goto yy75;
	yych = *++m_cursor;
	if (yych == 'W') goto yy424;
	if (yych != 'w') goto yy75;
yy424:
	yych = *++m_cursor;
	if (yych == 'I') goto yy425;
	if (yych != 'i') goto yy75;
yy425:
	yych = *++m_cursor;
	if (yych == 'T') goto yy426;
	if (yych != 't') goto yy75;
yy426:
	yych = *++m_cursor;
	if (yych == 'H') goto yy427;
	if (yych != 'h') goto yy75;
yy427:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= '@') {
		if (yych <= '\'') {
			if (yych >= '\'') goto yy75;
		} else {
			if (yych <= '/') goto yy428;
			if (yych <= '9') goto yy75;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy75;
			if (yych >= '_') goto yy75;
		} else {
			if (yych <= '`') goto yy428;
			if (yych <= 'z') goto yy75;
		}
	}
yy428:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_notStartsWith; }
yy430:
	yych = *++m_cursor;
	if (yych == 'N') goto yy431;
	if (yych != 'n') goto yy58;
yy431:
	yych = *++m_cursor;
	if (yych == 'T') goto yy432;
	if (yych != 't') goto yy58;
yy432:
	yych = *++m_cursor;
	if (yych == 'A') goto yy433;
	if (yych != 'a') goto yy58;
yy433:
	yych = *++m_cursor;
	if (yych == 'I') goto yy434;
	if (yych != 'i') goto yy58;
yy434:
	yych = *++m_cursor;
	if (yych == 'N') goto yy435;
	if (yych != 'n') goto yy58;
yy435:
	yych = *++m_cursor;
	if (yych == 'S') goto yy436;
	if (yych != 's') goto yy58;
yy436:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_contains; }
yy439:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy448;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	goto yy448;
yy440:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych <= 'D') {
		if (yych <= '/') {
			if (yych == '\'') goto yy57;
			goto yy444;
		} else {
			if (yych <= '9') goto yy57;
			if (yych <= '@') goto yy444;
			if (yych <= 'C') goto yy57;
			goto yy443;
		}
	} else {
		if (yych <= '`') {
			if (yych <= 'Z') goto yy57;
			if (yych == '_') goto yy57;
			goto yy444;
		} else {
			if (yych == 'd') goto yy443;
			if (yych <= 'z') goto yy57;
			goto yy444;
		}
	}
yy441:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_ignored; }
yy443:
	m_ctxmarker = m_cursor + 1;
	yych = *++m_cursor;
	if (yych & ~0xFF) {
		goto yy446;
	} else if (yybm[0+yych] & 16) {
		goto yy57;
	}
	goto yy446;
yy444:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_ignored; }
yy446:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_and; }
yy448:
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_as; }
yy450:
	m_ctxmarker = m_cursor + 1;
	++m_cursor;
	if (m_end <= m_cursor) { Fill(); }
	yych = *m_cursor;
yy451:
	if (yych & ~0xFF) {
		goto yy450;
	} else if (yybm[0+yych] & 32) {
		goto yy450;
	}
	if (yych >= 0x0001) goto yy454;
	++m_cursor;
	m_cursor = m_ctxmarker;
	{ return RelevanceToken::t_unterminatedString; }
yy454:
	++m_cursor;
	{ return RelevanceToken::t_string; }
yy456:
	++m_cursor;
	if (m_end <= m_cursor) { Fill(); }
	yych = *m_cursor;
yy457:
	if (yych & ~0xFF) {
		goto yy5;
	} else if (yybm[0+yych] & 64) {
		goto yy456;
	}
	goto yy5;
yy458:
	++m_cursor;
	if (m_end <= m_cursor) { Fill(); }
	yych = *m_cursor;
yy459:
	if (yych & ~0xFF) {
		goto yy3;
	} else if (yybm[0+yych] & 128) {
		goto yy458;
	}
	goto yy3;
}

}
